---
title: "Revisiting the SAFE Framework in the Statcast Era: A Modernized Approach to Evalutating MLB Infield Defense"
author:
  - name: Tyler McCord
    corresponding: true
    email: tmccord26@amherst.edu
    affiliations:
      - Amherst College
keywords: Sports analytics, Baseball defense, Probit regression, Hierarchical models
abstract: |
  High resolution tracking data has transformed player evaluation in Major League Baseball (MLB), enabling high-level analysis of player performance. While public analyses on batting and pitching have advanced rapidly, defensive evaluation has been comparatively underdeveloped. The SAFE (Spatially Adjusted Fielding Evaluation) framework, introduced by @jensen_2009, was the first effort in the public sphere to evaluate defense as a continuous space. We revisit the SAFE framework using modern Statcast data with an emphasis on infield defense, a notable struggle for prior defensive metrics. We reproduce the framework using hierarchical probit regression models and develop a defensive evaluation metric that exhibits modest correlations with existing publicly-available measures of defensive performance.
date: last-modified
bibliography: references.bib
number-sections: true
editor: 
  markdown: 
    wrap: sentence
---

## Introduction

The evaluation of batting and pitching in baseball has been at the forefront of sports analytics for decades, mostly due to their discrete nature and the availability of relevant, quantifiable data.
It is relatively simple to measure the outcome of a plate appearance or a pitch, making it easier to develop metrics that accurately reflect player performance in these areas.
In contrast, defensive evaluation in the public sphere has lagged behind due to the continuous, spatiotemporal nature of fielding.

Still, Major League Baseball (MLB) organizations are faced with important decisions regarding defense, such as positioning players, making defensive substitutions, and evaluating trade-offs between offensive and defensive abilities.
At the end of each season, MLB issues Gold Glove awards to the best defenders at each position, highlighting the importance of defense in the game.

Before the advent of high-resolution player tracking data, teams relied on simple defensive metrics such as fielding percentage, which calculates the percentage of plays a fielder successfully makes.
This depends on errors, which are charged when a fielder does not make a play that an average fielder would be expected to make.
However, errors are prone to subjectivity, as they depend primarily on the official scorer's judgement.
These metrics also fail to capture the full scope of a player's defensive contributions, as they do not account for factors such as range, positioning, and the difficulty of plays made.

Statisticians have tried to find ways to quantify the nuances of defense.
In 2003, Mitchel Lichtman introduced the Ultimate Zone Rating (UZR) metric, which attempted to evaluate defense by dividing the field into discrete zones and assigning run values to plays made or not made within those zones (@uzr_fangraphs).
This run-based approach allowed statisticians to understand the stakes of each defensive play.
However, many criticisms of UZR exist, including the arbitrary nature of the zone definitions and the discretization of a continuous space.

@jensen_2009 introduced the SAFE (Spatially Adjusted Fielding Evaluation) framework, which built upon UZR by using a hierarchical Bayesian model to evaluate defense as a continuous surface.
The SAFE framework uses estimates of player location, ball location, and ball velocity to model the probability of a fielder making a play on a batted ball, allowing for a more nuanced evaluation of defensive performance.
The model combines the probability of a made play with the run consequences of that play to estimate the overall defensive contribution of a player in terms of runs saved or allowed.
The hierarchical Bayesian structure also allows for the sharing of information across players and positions, improving estimates for players with limited data.
However, this model is limited by the accuracy and reliability of the underlying data used to estimate player and ball locations.
These data, provided by Baseball Info Solutions, used hand-annotated video footage to estimate ball location, player location, and velocity.

Since the publication of the SAFE framework, MLB has introduced Statcast, a high-resolution player tracking system that uses a combination of radar and camera technology to track the movement of players and the ball in real-time (need to find a citation).
Statcast provides a wealth of data that was previously unavailable, including precise measurements of player and ball locations, velocities, and trajectories.
This data has the potential to revolutionize defensive evaluation in baseball, allowing for more accurate and reliable estimates of defensive performance.

The goal of this paper is to modernize the original SAFE framework for infielders using three years of Statcast data (2023-2025).
We estimate the number of runs saved or cost by infielders at each position (1B, 2B, SS, 3B) in each year from 2023-2025 using modern data.
We fit hierarchical probit regression models similar to that of @jensen_2009 to estimate the probability of a ground ball resulting in a successful play by the fielder at each infield position (1B, 2B, SS, 3B).
We then convert these probability estimates into run values by estimating the run consequence of a given ground ball based on its location and velocity.

We extend the original framework to include player-specific positioning data from Baseball Savant to improve our estimates of fielder starting locations.
We evaluate our models by verifying that they produce reasonable results and by comparing our results to established and publicly-available defensive metrics.

## Data

Our evaluation of infield defense is based on Statcast data from 2023-2025.
Although Statcast data has been publicly available since 2015, we focus on the most recent three years because the infield "shift" was banned following the 2022 season.
We believe that narrowing the frame of our analysis to non-shifted seasons will yield more accurate estimates due to more consistent estimates for fielder locations.
We obtain data on batted balls through the `baseballr` package in R, which provides an interface for scraping Statcast data from MLB's public API.
The result is an .Rds file for each year of interest where each observation corresponds to a single batted ball in play (BIP) event.
Further, as an extension of the original SAFE framework, we extract information on individual player positioning before each pitch by using the "Fielder Positioning" page on Baseball Savant (@savant_positioning).
The location for each infielder on a given play is not publicly available.
However, Baseball Savant provides average positioning data for each player at each position based on all batted balls successfully fielded by that position.
We extract these data by downloading the relevant .csv files from the Baseball Savant website.

For each batted ball in play, we extract the relevant information needed to identify the fielder responsible for making a play, the location and velocity of the batted ball, and the outcome of the play.

Using these data, we derive the following factors for each batted ball:

-   **successful_play**: A binary indicator of whether the fielder successfully made a play on the batted ball (1 = successful play, 0 = unsuccessful play). For ground balls, this is defined as whether the fielder was able to field the ball and record at least one out.
-   **play_made_by**: The position (1B, 2B, SS, 3B) of the fielder who made the play on the batted ball (Other, if play is not successful or play is made by another position).
-   **location_x, location_y**: The $(x, y)$ coordinates of the batted ball when it reaches the fielder's location, measured in feet from home plate. The origin (0, 0) is at home plate, with the positive x-axis extending towards first base and the positive y-axis extending towards second base.
-   **spray_angle**: Derived from the $(x, y)$ coordinates, this angle represents the direction of the batted ball relative to home plate, measured in degrees. The first base foul line is 45 degrees, second base is 0 degrees, and the third base foul line is -45 degrees.
-   **launch_speed**: The velocity at which a ball is hit off the bat, measured in miles per hour (mph).

The resulting dataset contains 21 variables from 144,169 ground balls hit into fair territory from the 2023-2025 seasons.

{{< embed notebooks/exploratory.qmd#tbl-bip-summary >}}

{{< embed notebooks/exploratory.qmd#tbl-continuous-summary >}}

@tbl-bip-summary shows summary statistics for ground balls hit into fair territory from the 2023-2025 seasons.
The proportion of ground balls resulting in outs and the number of outs recorded at each infield position are consistent across the three seasons.

{{< embed notebooks/exploratory.qmd#fig-fielder-positioning >}}

We derive the starting location of the fielder at each position by calculating the average $(x, y)$ coordinates of all batted balls successfully fielded by that position, following the implementation by @jensen_2009.
@fig-fielder-positioning shows the calculated average fielder positioning for each infield position based on batted balls successfully fielded from the 2023-2025 seasons.
Note that although our analysis is only focused on ground balls, we use all batted balls successfully fielded by each position to estimate the average starting location of the fielder at that position, as in the original SAFE framework.
This intuitively makes sense, as the starting position of the fielder should not depend on the type of batted ball hit.

## Methods

The original SAFE framework follows a two-step process.
The first step is to estimate the probability that a fielder makes a successful play on a ground ball.
The second step is to estimate and apply the run consequence of a given play, which is then combined with the probability estimates to derive an overall defensive metric for each player.
In other words, each player is assigned a positive or negative run value based on the expected number of runs they save or cost their team for a given play with respect to the difficulty of the play.
We estimate SAFE values for each infielder in each year:

$$
SAFE_{i,p,y} = \sum_{\theta} \sum_{V} PPA_{i,p,y}(\theta, V) \times \Delta_{RE}(\theta, V) \times f(\theta, V) \times N_{opp}
$$

where $PPA_{i,p,y}$ is the play probability added for player $i$ at position $p$ in year $y$, $\Delta_{RE}$ is the change in run expectancy for a batted ball with spray angle $\theta$ and velocity $V$, and $f(\theta, V)$ is the density of batted balls hit with spray angle $\theta$ and velocity $V$.

Within a given position, we only consider plays in which the fielder at that position either made a successful play on the batted ball or nobody made a successful play on the batted ball.
This follows from the original SAFE framework, which only considers plays that the fielder at the given position had a chance to make.
We also only consider batted balls hit into fair territory.
Further, for each combination of year and position, we only consider players who had at least 300 plays at that position during that year, to aid in model convergence.

This process requires us to fit a model for each combination of position (1B, 2B, SS, 3B) and year (2023, 2024, 2025), resulting in a total of 12 models.
@jensen_2009 uses a Bayesian hierarchical probit regression model to estimate the probability of a successful play on a batted ball.
However, due to the large number of models to fit and the computational complexity of Bayesian methods, we use a frequentist hierarchical probit regression model for this analysis.

### Modeling The Probability of a Successful Play on a Ground Ball

A successful play on a ground ball is one in which the fielder records at least one out on the play.
Then, we can define each batted ball $j$ as a Bernoulli trial with outcome $S_{ij} = 1$ if player $i$ made a successful play and $S_{ij} = 0$ otherwise.
Then, we define:

$$
S_{ij} = \text{Bernoulli}(p_{ij})
$$ where $p_{ij}$ is the probability that fielder $i$ makes a successful play on batted ball $j$.

We model this probability as a function of the velocity of the batted ball ($V_{ij}$), the angle ($\theta_{ij}$) between the fielder's starting position and the location of the batted ball, and an indicator for whether the fielder must move left or right to make the play ($L_{ij} = 1$ for left, $L_{ij} = 0$ for right):

$$
p_{ij} = \Phi(\beta_{i0} + \beta_{i1} \theta_{ij} + \beta_{2} \theta_{ij} L_{ij} + \beta_{3} \theta_{ij} V_{ij} + \beta_{4} \theta_{ij} V_{ij} L_{ij})
$$

where $\Phi$ is the standard normal cumulative distribution function (CDF).
It's important to note that the coefficients $\beta_{ik}$ for $k = 0, 1$ are player-specific, while the coefficients $\beta_{k}$ for $k = 2, 3, 4$ are shared across all players at that position.
Our model specification includes random intercept effects for each fielder, as well as random slope effects for the angle terms.
We allow each player to have a different baseline for fielding a given ground ball and a different slope for the angle terms.
This reflects our belief that different players may have different abilities to field balls hit at different angles.
The original Bayesian implementation of this model used player-specific coefficients for all terms, but we simplify this hierarchical structure to reduce computational complexity and improve model convergence.

We fit this model using the `lme4` package in R.
We utilize the `glmer` function using the `family = "probit"` parameter to specify probit regression.

{{< embed notebooks/prob_model_example.qmd#fig-random-intercepts >}}

@fig-random-intercepts demonstrates individual player random intercepts for shortstops (SS) in the 2025 season.
Players differ in their baseline abilities.
However, the standard error of these estimates are large such that most of the players' random intercepts are not significantly positive or negative.

### Measuring the Quality of a Play

Under this model, we calculate the estimated probability of a successful play for each batted ball in our dataset by using the fitted model for the relevant position and year.
However, we are interested in calculating the probability that a player makes a successful play above the probability that an average player at that position would make a successful play on that batted ball.
Then, for each batted ball, for a given player, we calculate the play probability added (PPA) as the difference between the estimated probability that that player makes a successful play and the estimated probability that an average player at that position would make a successful play:

$$
PPA_{ij} = \hat{p}_{ij}^{(player)} - \hat{p}_{j}^{(avg)}
$$

where $\hat{p}_{ij}^{(player)}$ is the estimated probability that player $i$ makes a successful play on batted ball $j$, and $\hat{p}_{j}^{(avg)}$ is the estimated probability from the same model, but assumes that player-specific coefficients are 0.
We can interpret this value as the additional probability that player $i$ makes a successful play on batted ball $j$ above the average probability that any player at that position would make a successful play on that batted ball.

This is preferred to simply using the residual values from the player-specific model because it is desirable to compare the probability that a given player makes a successful play to the average probability that any player at that position would make a successful play on that batted ball.

### Measuring the Run Consequences of Ground Balls

Consider two different hard-hit ground balls that a third basemen receives, one to his left, and one to his right, each with equally difficult success probabilities.
A ground ball hit to his side closest to the shortstop is most likely to result in a single.
However, the ground ball hit closer to the left field foul line is more likely to result in a double.
Although we would consider these plays equally difficult, the run consequences of each play, if they are not successful, are quite different.
Then, we need to account for the number of runs that a fielder is saving the team if he makes a successful play on a given batted ball, or the number of runs he is costing the team if he does not make a successful play.

Each play is associated with a change in expected runs for the defensive team, which we denote as $\Delta_{RE}$.
This value is calculated as the difference in run expectancy before and after the play.
We only consider the change in run expectancy for unsuccessful plays, as we are interested in quantifying the consequences of not making a successful play on a batted ball.
We fit a generalized additive model (GAM) to estimate the run consequence $\Delta_{RE}$ of an unsuccessful ground ball $j$ based on its launch speed $V_j$ and spray angle $\theta_j$:

$$
\Delta_{RE, j} = f(V_j) + f(\theta_j) + V_j\theta_j + \epsilon
$$

where $f$ represents a smooth function estimated by the GAM.

We fit the GAM using the `gam` function in the `mgcv` package in R.

### Calculating the Density of Batted Balls

Finally, we need to estimate the density of batted balls $f(\theta, V)$ hit with spray angle $\theta$ and velocity $V$.
This density is estimated using a two-dimensional kernel density estimate (KDE) based on the observed distribution of batted balls in our dataset.
We do this using the `kde2d` function from the `ks` package in R.
This gives an estimate of the density of batted balls hit with different combinations of spray angle and velocity, which accounts for the frequency of different types of batted balls.

### Estimating Player SAFE Values

Finally, we calculate the SAFE value for each player $i$ at position $p$ in year $y$ by summing over a space of plausible values of $\theta$ and $V$.
For each combination of $\theta$ and $V$, we calculate the expected run value added/lost by player $i$ as:

$$
SAFE_{i,p,y} = \sum_{\theta} \sum_{V} PPA_{i,p,y}(\theta, V) \times \Delta_{RE}(\theta, V) \times f(\theta, V) \times N_{opp}
$$

This gives us an overall estimate of the number of runs saved or cost by player $i$ at position $p$ in year $y$ based on their defensive performance on ground balls.
We scale this by $N\_{opp}$ to account for the number of opportunities that a player gets in a given season.

{{< embed notebooks/probability_modeling.qmd#fig-safe-components >}}

@fig-safe-components illustrates how the different components of SAFE come together to produce a final SAFE value using a hypothetical player.
We illustrate this point using Andres Gimenez, a second baseman for the Cleveland Guardians in the 2023 season.
For simplicity, we illustrate this process using a ball hit at a fixed velocity of 90 mph.
The top left panel shows the estimated play probability added (PPA) for Gimenez on balls hit at different spray angles.
There are two curves: one for Andres Gimenez, and another representing an average second baseman.
The difference in these curves for a given spray angle represents the $PPA$ for Gimenez.
The top right panel shows the estimated run consequence $\Delta_{RE}$ for unsuccessful plays at different spray angles.
The bottom left panel shows the density of batted balls, $f(\theta, V)$, hit at different spray angles.
Finally, the bottom right panel shows the product of these three components and the number of opportunities, which represents the contribution to SAFE for Gimenez at each spray angle.
This plot shows which types of plays at 90 mph are resulting in the most contributions to SAFE for Gimenez.
The area under this curve represents the total SAFE value for Gimenez at a velocity of 90 mph.
We integrate over all plausible velocities to get the final SAFE value.

### Updated SAFE with Player-Specific Positioning

The original SAFE model attempts to estimate the starting location of each position by using the average location of all batted balls successfully fielded by that position.
This assumes that all players at a given position start from the same location, which is unlikely to be true in practice.
It also assumes a direct relationship between the location of successfully fielded balls and the starting position of the fielder, which may not hold if players have different ranges or positioning strategies.
However, we can improve upon this estimate by using the average positioning location for each individual player at each position using Baseball Savant.
We believe this captures the nuances of each player's defensive positioning, which may vary significantly from the average positioning for that position.

For this model extension, we follow the same model structure as prior.
We hypothesize that a more accurate estimate of individual fielding starting position will give a better estimation of distance, angle, and direction for a given batted ball.

{{< embed notebooks/probability_modeling.qmd#fig-statcast-positioning >}}

## Results

For each combination of position and year, we calculate the SAFE values for each player using both the original SAFE model and the updated SAFE model with player-specific positioning data.
It's important to note that select year/position combinations did not converge and thus SAFE values could not be calculated for players in those groups.
We focus our evaluation in this section on the SAFE model without player-specific positioning.
We evaluate our model in two ways.

First, we verify that our model produces reasonable results by maintaining the desired result that players at more valuable positions like shortstop and second base tend to have higher SAFE values than players at less valuable positions like first base.
We also check that our model produces the desirable result that players with fewer opportunities tend to have SAFE values closer to zero, as they have less data to inform their estimates and should be considered close to average.
Second, we check that our model correlates well with two established metrics, Defensive Runs Saved (DRS) and Outs Above Average (OAA), both provided by Baseball Savant.

### Internal Evaluation

SAFE is calculated to be a runs saved above average metric, so we expect first that the distribution of SAFE values should be centered around zero for each position and year.
Further, we expect that players with fewer opportunities should have SAFE values closer to zero, as they have less data to inform their estimates and should be considered close to average.

{{< embed notebooks/results.qmd#fig-safe-distributions >}}

As expected, the distribution of SAFE values is centered around zero for each position.
Note that first basemen tend to have more players with values closer to 0.
This is a desired result, as first base is generally considered a less valuable defensive position, so we expect fewer players to have extreme positive or negative SAFE values at that position.

We also see that players with fewer opportunities tend to have SAFE values closer to zero, as expected.
Recall that we limited our analysis to players with at least 300 opportunities in a given year/position combination to ensure model convergence.
For this reason, the effect of small sample size on SAFE values is less pronounced than it might be if we included players with far fewer opportunities.

We focus on highlighting the top 5 players at a given position.

{{< embed notebooks/results.qmd#tbl-top-ss-2025 >}}

@tbl-top-ss-2025 shows that Jeremy Pena was the best defender at SS in 2025 according to our SAFE estimates, saving an estimated 2.49 runs above average over the course of the season.
Due to spatial constraints, more of these results are shown in the Appendix. 

### External Evaluation

We compare our estimates to two public defensive metrics, Defensive Runs Saved (DRS) and Outs Above Average (OAA).
It's important to note that the SAFE metric only considers ground balls, while DRS and OAA consider all batted balls.
DRS is a more comparable metric in its interpretation, as it estimates runs saved above average.
Still, we expect that our SAFE estimates should correlate reasonably well with these established metrics.

{{< embed notebooks/results.qmd#tbl-safe-correlations >}}

{{< embed notebooks/results.qmd#tbl-safe-correlations-by-position >}}

@tbl-safe-correlations shows that our estimates correlate well with DRS, but not as well with OAA, on average.
When breaking down the correlations by position in @tbl-safe-correlations-by-position, we notice that our estimates correlate best for second basemen, and struggle the most with first basemen.
It's important to note that there is no "gold standard" for defensive evaluation.
Different metrics capture different aspects of defensive performance.
However, we believe that it's an important validation step to ensure that our estimates align reasonably well with established metrics in the field.

### Note on Player-Specific Positioning Results

We found that incorporating player-specific positioning data from Baseball Savant did not improve the model's performance in terms of correlation with established defensive metrics like DRS and OAA.
In fact, the correlations, on average, were slightly worse when using player-specific positioning data.
There were some position-specific improvements, but overall, the results were mixed.

Notably, we observe that this model extension tends to over-value less important positions like first base.

We show comparable results of this model extension in the supplementary materials.

## Conclusion

We produced SAFE estimates for infielders from the 2023-2025 MLB seasons by reproducing and modernizing a subsection of the original SAFE framework using Statcast data.
Although we were not able to implement the full Bayesian hierarchical probit regression model from @jensen_2009 due to computational constraints, we fit a frequentist hierarchical probit regression model that produced reasonable results.
Our results indicate that our SAFE estimates correlate reasonably well with established defensive metrics like DRS using high-resolution, publicly-available data.

### Limitations

There are several limitations to our analysis that should be noted.
First, we were not able to implement the full Bayesian hierarchical probit regression model from @jensen_2009 due to computational constraints.
Using the adjacent frequentist approach to fit hierarchical probit regression models limited our ability to consider players with fewer opportunities, as these models struggled to converge with limited data.
Then, the scope of our analysis was limited to infielders with at least 300 opportunities in a given year/position combination, which is roughly equivalent to an every day player.

Similarly, we were not able to incorporate all relevant fixed and player-specific covariates from the original paper into our model due to convergence issues.
We believe the the lack of some of these features may have limited the extent to which we were able to capture individual player defensive abilities.
As a result, our SAFE estimates are notable underestimations of those produced by @jensen_2009.

### Future Work

The SAFE framework combines the aspects of DRS and OAA, by considering both the difficulty of the play and the run consequences of the play.
Still, evaluating infield defense remains an unfinished task due to the complexity of defensive performance.
Future work could consider additional covariates about game state and baserunner personnel to better capture the context of each defensive play.
Additionally, it is of interest to evaluate the components of infield performance separately, such as range, arm strength, and decision making.

## References {.unnumbered}

::: {#refs}
:::

## Appendix

### Top Players by Position and Year

{{< embed notebooks/results.qmd#tbl-top-2b-2025 >}}

{{< embed notebooks/results.qmd#tbl-top-3b-2025 >}}

{{< embed notebooks/results.qmd#tbl-top-1b-2024 >}}


### Player-Specific Positioning SAFE Results

{{< embed notebooks/results.qmd#fig-safe-sc-distribution >}}

{{< embed notebooks/results.qmd#fig-safe-sc-n-opportunities >}}

{{< embed notebooks/results.qmd#tbl-safe-sc-correlations >}}

{{< embed notebooks/results.qmd#tbl-safe-sc-correlations-by-position >}}
