---
title: "SAFE Modeling Results"
format: html
---

```{r}
library(tidyverse)
library(kableExtra)
library(gridExtra)
```

```{r}
player_id_map <- read_rds("statcast_data/player_positioning/sc_positioning.rds") |>
  mutate(fielder_id = as.character(fielder_id)) |>
  dplyr::select(fielder_id, name_fielder) |>
  distinct()

safe_results <- read_rds("results/safe_results.rds") |>
  left_join(player_id_map, by = "fielder_id") |>
  rename(fielder_name = name_fielder) |>
  dplyr::select(fielder_id, fielder_name, position, year, n_opportunities, SAFE)

safe_sc_results <- read_rds("results/sc_safe_results.rds") |>
  left_join(player_id_map, by = "fielder_id") |>
  rename(fielder_name = name_fielder) |>
  dplyr::select(fielder_id, fielder_name, position, year, n_opportunities, SAFE)

oaa_drs <- read_rds("statcast_data/oaa_drs.rds") |>
  mutate(fielder_id = as.character(fielder_id))
```

## Distribution of SAFE Values

```{r}
#| label: fig-safe-distributions
#| fig-cap: "Distribution of SAFE Values by Position"
#| fig-width: 8
#| fig-height: 3

p_safe_dist <- safe_results |>
  ggplot(aes(x = SAFE, color = position)) +
  geom_density() +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", alpha = 0.6) +
  labs(
    title = "Distribution of SAFE Values by Position",
    x = "SAFE",
    y = "Density",
    color = "Position"
  ) +
  theme_classic()

p_safe_n_opp <- safe_results |>
  ggplot(aes(x = n_opportunities, y = SAFE, color = position)) +
  geom_point(alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", alpha = 0.6) +
  labs(
    x = "Number of Opportunities",
    y = "SAFE",
    color = "Position"
  ) +
  theme_classic()

grid.arrange(p_safe_dist, p_safe_n_opp, ncol = 2)
```

## Top 5 By Position for Select Combinations

```{r}
top_safe <- function(safe_results, position, year, n = 5) {
  safe_results |>
    filter(position == !!position, year == !!year) |>
    arrange(desc(SAFE)) |>
    slice_head(n = n) |>
    select(fielder_name, SAFE) |>
    mutate(SAFE = round(SAFE, 2))
}
```


```{r}
#| label: tbl-top-ss-2025
#| tbl-cap: "Top 5 Shortstops by SAFE in 2025"

top_safe(safe_results, "SS", 2025) |>
  kable(col.names = c("Fielder", "SAFE")) |>
  kable_styling(full_width = F)
```

```{r}
#| label: tbl-top-2b-2025
#| tbl-cap: "Top 5 Second Basemen by SAFE in 2025"

top_safe(safe_results, "2B", 2025) |>
  kable(col.names = c("Fielder", "SAFE")) |>
  kable_styling(full_width = F)
```

```{r}
#| label: tbl-top-3b-2025
#| tbl-cap: "Top 5 Third Basemen by SAFE in 2025"

top_safe(safe_results, "3B", 2025) |>
  kable(col.names = c("Fielder", "SAFE")) |>
  kable_styling(full_width = F)
```

```{r}
#| label: tbl-top-1b-2024
#| tbl-cap: "Top 5 First Basemen by SAFE in 2024"

top_safe(safe_results, "1B", 2024) |>
  kable(col.names = c("Fielder", "SAFE")) |>
  kable_styling(full_width = F)
```


## Correlation with OAA and DRS

```{r}
#| label: tbl-safe-correlations
#| tbl-cap: "Correlation of SAFE with OAA and DRS. Each observation is year-position specific for each fielder."

safe_comparison <- safe_results |>
  inner_join(oaa_drs, by = c("fielder_id", "year", "position"))


safe_comparison |>
  summarize(
    OAA = cor(SAFE, OAA, use = "complete.obs"),
    DRS = cor(SAFE, DRS, use = "complete.obs")
  ) |>
  mutate(metric = "SAFE") |>
  select(metric, everything()) |>
  kable(col.names = c("Metric", "OAA", "DRS")) |>
  kable_styling(full_width = F)
```

```{r}
#| label: tbl-safe-correlations-by-position
#| tbl-cap: "Correlation of SAFE with OAA and DRS by Position. Each observation is year-position specific for each fielder."

safe_comparison |>
  group_by(position) |>
  summarize(
    OAA = cor(SAFE, OAA, use = "complete.obs"),
    DRS = cor(SAFE, DRS, use = "complete.obs")
  ) |>
  kable(col.names = c("Position", "SAFE-OAA", "SAFE-DRS")) |>
  kable_styling(full_width = F)
```

## Player-Specific Positioning Results

```{r}
#| label: fig-safe-sc-distribution
#| fig-cap: "Distribution of SAFE Values from Statcast Positioning Model by Position"

ggplot(safe_sc_results, aes(x = SAFE, color = position)) +
  geom_density() +
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", alpha = 0.6) +
  labs(
    title = "Distribution of SAFE Values from Statcast Positioning Model by Position",
    x = "SAFE (Statcast Positioning)",
    y = "Density",
    color = "Position"
  ) +
  theme_classic()
```


```{r}
#| label: fig-safe-sc-n-opportunities
#| fig-cap: "SAFE from Statcast Positioning vs. Number of Opportunities"

safe_sc_results |>
  ggplot(aes(x = n_opportunities, y = SAFE, color = position)) +
  geom_point(alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black", alpha = 0.6) +
  labs(
    x = "Number of Opportunities",
    y = "SAFE (Statcast Positioning)",
    color = "Position"
  ) +
  theme_classic()
```


```{r}
#| label: tbl-safe-sc-correlations
#| tbl-cap: "Correlation of SAFE from Statcast Positioning with OAA and DRS. Each observation is year-position specific for each fielder."

safe_sc_comparison <- safe_sc_results |>
  inner_join(oaa_drs, by = c("fielder_id", "year", "position"))

safe_sc_comparison |>
  summarize(
    OAA = cor(SAFE, OAA, use = "complete.obs"),
    DRS = cor(SAFE, DRS, use = "complete.obs")) |>
  mutate(metric = "SAFE (Statcast Positioning)") |>
  select(metric, everything()) |>
  kable(col.names = c("Metric", "OAA", "DRS")) |>
  kable_styling(full_width = F)


```

```{r}
#| label: tbl-safe-sc-correlations-by-position
#| tbl-cap: "Correlation of SAFE from Statcast Positioning with OAA and DRS by Position. Each observation is year-position specific for each fielder."
safe_sc_comparison |>
  group_by(position) |>
  summarize(
    OAA = cor(SAFE, OAA, use = "complete.obs"),
    DRS = cor(SAFE, DRS, use = "complete.obs")
  ) |>
  kable(col.names = c("Position", "SAFE (Statcast Positioning)-OAA", "SAFE (Statcast Positioning)-DRS")) |>
  kable_styling(full_width = F)
```

